"""empty message

Revision ID: 57165dc16362
Revises: 9d43ff52384c
Create Date: 2022-05-27 23:56:33.050757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57165dc16362'
down_revision = '9d43ff52384c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column(
        'created_date', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column(
        'created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created_date')
    op.drop_column('Artist', 'created_date')
    # ### end Alembic commands ###
