"""empty message

Revision ID: 5a38652c0598
Revises: daaac31264e3
Create Date: 2022-05-21 02:50:32.950868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a38652c0598'
down_revision = 'daaac31264e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Artist_id'], ['Artist.id'], name='Show_Artist_id_fkey'),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], name='Show_Venue_id_fkey'),
    sa.PrimaryKeyConstraint('Artist_id', 'Venue_id', name='Show_pkey')
    )
    op.drop_table('show')
    # ### end Alembic commands ###
