"""empty message

Revision ID: a984cda0cf9f
Revises: a9d7c161ee6f
Create Date: 2022-05-23 01:08:24.614798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a984cda0cf9f'
down_revision = 'a9d7c161ee6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'num_of_upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Venue', 'num_of_upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
