"""empty message

Revision ID: c63d12d88ac8
Revises: 
Create Date: 2022-05-20 20:38:41.712139

"""
from email.policy import default
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63d12d88ac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=False))
    op.add_column('Venue', sa.Column('num_of_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False),default=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'num_of_upcoming_shows')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
