"""empty message

Revision ID: daaac31264e3
Revises: c63d12d88ac8
Create Date: 2022-05-20 22:54:11.698723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaac31264e3'
down_revision = 'c63d12d88ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('website_link', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
